In [1]:
from __future__ import print_function
import torch as t

In [3]:
a = t.Tensor(2, 3)
a

tensor([[3.3319e-16, 8.5619e-43, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00]])

In [5]:
b = t.Tensor([[1,2,3], [4,5,6]])
b

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [7]:
b.tolist()

[[1.0, 2.0, 3.0], [4.0, 5.0, 6.0]]

In [9]:
b_size = b.size()
b_size

torch.Size([2, 3])

In [11]:
b.numel()

6

In [13]:
c = t.Tensor(b_size)
d = t.Tensor((2, 3))
c, d

(tensor([[3.3320e-16, 8.5619e-43, 0.0000e+00],
         [0.0000e+00, 0.0000e+00, 0.0000e+00]]),
 tensor([2., 3.]))

In [15]:
type(b_size)

torch.Size

In [17]:
type((2,3))

tuple

In [19]:
c.shape

torch.Size([2, 3])

In [21]:
c.shape??

Type:            Size
String form:     torch.Size([2, 3])
Length:          2
File:            c:\users\sifanzhang\appdata\local\anaconda3\lib\site-packages\torch\__init__.py
Docstring:       <no docstring>
Class docstring:
Built-in immutable sequence.

If no argument is given, the constructor returns an empty tuple.
If iterable is specified the tuple is initialized from iterable's items.

If the argument is a tuple, the return value is the same object.

In [23]:
t.ones(2, 3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [25]:
t.zeros(2, 3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [27]:
t.arange(1, 6, 2)

tensor([1, 3, 5])

In [29]:
t.linspace(1, 10, 3)

tensor([ 1.0000,  5.5000, 10.0000])

In [31]:
t.randn(2, 3)

tensor([[-0.4827,  0.0083,  1.4278],
        [ 0.4239,  0.3735, -1.6797]])

In [33]:
t.randperm(5)

tensor([0, 3, 4, 2, 1])

In [35]:
t.eye(2, 3)

tensor([[1., 0., 0.],
        [0., 1., 0.]])

In [39]:
a = t.arange(0, 6)
a.view(2, 3)

tensor([[0, 1, 2],
        [3, 4, 5]])

In [45]:
a.view(6, -1)

tensor([[0],
        [1],
        [2],
        [3],
        [4],
        [5]])

In [47]:
b = a.view(-1, 3)

In [49]:
b.shape

torch.Size([2, 3])

In [55]:
b = b.unsqueeze(1)

In [57]:
b.shape

torch.Size([2, 1, 3])

In [59]:
b.unsqueeze(-2)

tensor([[[[0, 1, 2]]],


        [[[3, 4, 5]]]])

In [61]:
b.shape

torch.Size([2, 1, 3])

In [63]:
c = b.view(1, 1, 1, 2, 3)
c

tensor([[[[[0, 1, 2],
           [3, 4, 5]]]]])

In [65]:
c.squeeze(0)

tensor([[[[0, 1, 2],
          [3, 4, 5]]]])

In [71]:
c.squeeze(0).shape

torch.Size([1, 1, 2, 3])

In [73]:
c.squeeze().shape

torch.Size([2, 3])

In [75]:
a[1] = 100
b

tensor([[[  0, 100,   2]],

        [[  3,   4,   5]]])

In [77]:
b

tensor([[[  0, 100,   2]],

        [[  3,   4,   5]]])

In [79]:
b.resize_(1, 3)

tensor([[  0, 100,   2]])

In [81]:
b.resize_(3, 3)

tensor([[  0, 100,   2],
        [  3,   4,   5],
        [  0,   0,   0]])

In [83]:
a = t.randn(3, 4)
a

tensor([[ 1.5425, -0.2761,  0.6234,  0.8898],
        [ 0.1555,  0.8459,  0.0490,  1.1181],
        [ 0.3152, -0.2681, -0.7664,  0.0121]])

In [85]:
a[0]

tensor([ 1.5425, -0.2761,  0.6234,  0.8898])

In [87]:
a[:, 0]

tensor([1.5425, 0.1555, 0.3152])

In [89]:
a[0][2]

tensor(0.6234)

In [91]:
a[0][-1]

tensor(0.8898)

In [93]:
a[:2]

tensor([[ 1.5425, -0.2761,  0.6234,  0.8898],
        [ 0.1555,  0.8459,  0.0490,  1.1181]])

In [95]:
a[:2, 0:2]

tensor([[ 1.5425, -0.2761],
        [ 0.1555,  0.8459]])

In [97]:
a[0:1, :2]

tensor([[ 1.5425, -0.2761]])

In [99]:
a[0, :2]

tensor([ 1.5425, -0.2761])

In [101]:
a > 1

tensor([[ True, False, False, False],
        [False, False, False,  True],
        [False, False, False, False]])

In [103]:
a[a>1]

tensor([1.5425, 1.1181])

In [105]:
a[t.LongTensor([0, 1])]

tensor([[ 1.5425, -0.2761,  0.6234,  0.8898],
        [ 0.1555,  0.8459,  0.0490,  1.1181]])

In [111]:
a = t.arange(0, 16).view(4, 4)
a

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]])

In [113]:
index = t.LongTensor([[0, 1, 2, 3]])
a.gather(0, index)

tensor([[ 0,  5, 10, 15]])

In [115]:
a.gather(1, index)

tensor([[0, 1, 2, 3]])

In [117]:
index = t.LongTensor([[3, 2, 1, 0]]).t()
index

tensor([[3],
        [2],
        [1],
        [0]])

In [121]:
a.gather(1, index)

tensor([[ 3],
        [ 6],
        [ 9],
        [12]])

In [123]:
index = t.LongTensor([[3, 2, 1, 0]])
a.gather(0, index)

tensor([[12,  9,  6,  3]])

In [129]:
index = t.LongTensor([[0,1,2,3],[3,2,1,0]]).t()
b = a.gather(1, index)
b

tensor([[ 0,  3],
        [ 5,  6],
        [10,  9],
        [15, 12]])

In [139]:
index.dtype
b.dtype

torch.int64

In [149]:
c = t.zeros((4, 4), dtype=t.int64)
c.dtype
c.scatter_(1, index, b)
c

tensor([[ 0,  0,  0,  3],
        [ 0,  5,  6,  0],
        [ 0,  9, 10,  0],
        [12,  0,  0, 15]])

In [151]:
x = t.arange(0, 27).view(3, 3, 3)
x

tensor([[[ 0,  1,  2],
         [ 3,  4,  5],
         [ 6,  7,  8]],

        [[ 9, 10, 11],
         [12, 13, 14],
         [15, 16, 17]],

        [[18, 19, 20],
         [21, 22, 23],
         [24, 25, 26]]])

In [155]:
x.shape

torch.Size([3, 3, 3])

In [157]:
x[[1, 2], [1, 2], [2, 0]] # 组合索引

tensor([14, 24])

In [159]:
x[[2, 1, 0], [0], [1]]

tensor([19, 10,  1])

In [161]:
x[[0, 2], ...]

tensor([[[ 0,  1,  2],
         [ 3,  4,  5],
         [ 6,  7,  8]],

        [[18, 19, 20],
         [21, 22, 23],
         [24, 25, 26]]])

In [163]:
x[[0, 2]]

tensor([[[ 0,  1,  2],
         [ 3,  4,  5],
         [ 6,  7,  8]],

        [[18, 19, 20],
         [21, 22, 23],
         [24, 25, 26]]])

In [167]:
a = t.Tensor(2, 3)
a

tensor([[1.5425, 0.2761, 0.6234],
        [0.8898, 0.1555, 0.8459]])

In [169]:
b = a.float()
b

tensor([[1.5425, 0.2761, 0.6234],
        [0.8898, 0.1555, 0.8459]])

In [171]:
c = a.type_as(b)
c

tensor([[1.5425, 0.2761, 0.6234],
        [0.8898, 0.1555, 0.8459]])

In [173]:
d = a.new(2, 3)
d

tensor([[3.3323e-16, 8.5619e-43, 1.4278e+00],
        [4.2394e-01, 3.7355e-01, 1.6797e+00]])

In [175]:
a.new??

Docstring: <no docstring>
Type:      builtin_function_or_method

In [177]:
a ** 2

tensor([[2.3793, 0.0762, 0.3887],
        [0.7917, 0.0242, 0.7155]])

In [179]:
a

tensor([[1.5425, 0.2761, 0.6234],
        [0.8898, 0.1555, 0.8459]])

In [181]:
t.pow(a, 2)

tensor([[2.3793, 0.0762, 0.3887],
        [0.7917, 0.0242, 0.7155]])

In [183]:
a * 2

tensor([[3.0850, 0.5522, 1.2469],
        [1.7795, 0.3111, 1.6918]])

In [185]:
t.mul(a, 2)

tensor([[3.0850, 0.5522, 1.2469],
        [1.7795, 0.3111, 1.6918]])

In [187]:
a = t.arange(0, 6).view(2, 3)
t.cos(a)

tensor([[ 1.0000,  0.5403, -0.4161],
        [-0.9900, -0.6536,  0.2837]])

In [189]:
a % 3

tensor([[0, 1, 2],
        [0, 1, 2]])

In [191]:
t.fmod(a, 3)

tensor([[0, 1, 2],
        [0, 1, 2]])

In [193]:
a ** 2

tensor([[ 0,  1,  4],
        [ 9, 16, 25]])

In [195]:
t.clamp(a, min=3)

tensor([[3, 3, 3],
        [3, 4, 5]])

In [197]:
a

tensor([[0, 1, 2],
        [3, 4, 5]])

In [199]:
b = t.ones(2, 3)
b.sum(dim = 0, keepdim = True)

tensor([[2., 2., 2.]])

In [201]:
b.sum(dim = 0)

tensor([2., 2., 2.])

In [203]:
b.sum(dim=1)

tensor([3., 3.])

In [205]:
a = t.arange(0, 6).view(2, 3)
a

tensor([[0, 1, 2],
        [3, 4, 5]])

In [207]:
a.cumsum(dim = 1)

tensor([[ 0,  1,  3],
        [ 3,  7, 12]])

In [209]:
a = t.linspace(0, 15, 6).view(2, 3)
a

tensor([[ 0.,  3.,  6.],
        [ 9., 12., 15.]])

In [211]:
b = t.linspace(15, 0, 6).view(2, 3)
b

tensor([[15., 12.,  9.],
        [ 6.,  3.,  0.]])

In [213]:
a > b

tensor([[False, False, False],
        [ True,  True,  True]])

In [215]:
a[a > b]

tensor([ 9., 12., 15.])

In [217]:
t.max(a)

tensor(15.)

In [219]:
t.max(b, dim = 1)

torch.return_types.max(
values=tensor([15.,  6.]),
indices=tensor([0, 0]))

In [221]:
t.max(a, b)

tensor([[15., 12.,  9.],
        [ 9., 12., 15.]])

In [223]:
t.clamp(a, min = 10)

tensor([[10., 10., 10.],
        [10., 12., 15.]])

In [225]:
import numpy as np
a = np.ones([2, 3], dtype=np.float32)
a

array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)

In [227]:
b = t.from_numpy(a)
b

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [229]:
b = t.Tensor(a)
b

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [231]:
a[0, 1] = 100
b

tensor([[  1., 100.,   1.],
        [  1.,   1.,   1.]])

In [233]:
c = b.numpy()
c

array([[  1., 100.,   1.],
       [  1.,   1.,   1.]], dtype=float32)

In [235]:
a = t.ones(3, 2)
b = t.zeros(2, 3, 1)

In [237]:
a + b

tensor([[[1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.]]])

In [239]:
a.unsqueeze(0).expand(2, 3, 2) + b.expand(2, 3, 2)

tensor([[[1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.]]])

In [245]:
a = t.arange(0, 6)
a.storage()

C:\Users\sifanzhang\AppData\Local\Temp\ipykernel_29068\1698548709.py:2: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  a.storage()


 0
 1
 2
 3
 4
 5
[torch.storage.TypedStorage(dtype=torch.int64, device=cpu) of size 6]

In [247]:
b = a.view(2, 3)
b.storage()

 0
 1
 2
 3
 4
 5
[torch.storage.TypedStorage(dtype=torch.int64, device=cpu) of size 6]

In [249]:
id(b.storage()) == id(a.storage())

False

In [251]:
a[1] = 100

In [253]:
b

tensor([[  0, 100,   2],
        [  3,   4,   5]])

In [255]:
c = a[2:]
c.storage()

 0
 100
 2
 3
 4
 5
[torch.storage.TypedStorage(dtype=torch.int64, device=cpu) of size 6]

In [257]:
c.data_ptr()

2624858489424

In [259]:
a.data_ptr()

2624858489408

In [291]:
def for_loop_add(x, y):
    result = []
    for i, j in zip(x, y):
        result.append(i + j)
    return t.Tensor(result)

In [293]:
x = t.zeros(100)
y = t.ones(100)
%timeit -n 10 for_loop_add(x, y)

918 μs ± 242 μs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [295]:
%timeit -n 10 x + y

The slowest run took 12.92 times longer than the fastest. This could mean that an intermediate result is being cached.
15.4 μs ± 22.6 μs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [297]:
a = t.randn(2, 3)
a

tensor([[ 0.4411,  0.3635,  0.1008],
        [-0.4671,  0.0649, -0.9126]])