In [1]:
from __future__ import print_function
import torch as t
from torch.autograd import Variable as V

In [3]:
a = V(t.ones(3, 4), requires_grad = True)
a

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]], requires_grad=True)

In [5]:
b = V(t.zeros(3, 4))
b

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [7]:
c = a.add(b)
c

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]], grad_fn=<AddBackward0>)

In [9]:
d = c.sum()
d

tensor(12., grad_fn=<SumBackward0>)

In [11]:
d.backward()

In [13]:
c.data.sum()

tensor(12.)

In [15]:
c.sum()

tensor(12., grad_fn=<SumBackward0>)

In [17]:
a.grad

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [19]:
b.grad

In [21]:
a.is_leaf, b.is_leaf, c.is_leaf

(True, True, False)

In [25]:
c.grad is None

C:\Users\sifanzhang\AppData\Local\Temp\ipykernel_23768\1042261844.py:1: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the .grad field to be populated for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more informations. (Triggered internally at aten\src\ATen/core/TensorBody.h:494.)
  c.grad is None


True

#### 

In [29]:
x = V(t.randn(3, 4), requires_grad = True)
y = f(x)
y

tensor([[0.2933, 0.4651, 0.1193, 0.3648],
        [0.4958, 0.2743, 0.0519, 9.7027],
        [6.7985, 0.7434, 8.7057, 0.4523]], grad_fn=<MulBackward0>)

In [31]:
y.backward(t.ones(y.size()))
x.grad

tensor([[-0.4279, -0.2404, -0.4385, -0.3709],
        [-0.1814,  1.5688,  0.5568, 22.7832],
        [16.9717,  3.1057, 20.8156, -0.2614]])

In [33]:
gradf(x)

tensor([[-0.4279, -0.2404, -0.4385, -0.3709],
        [-0.1814,  1.5688,  0.5568, 22.7832],
        [16.9717,  3.1057, 20.8156, -0.2614]], grad_fn=<AddBackward0>)

In [35]:
x = V(t.ones(1))
b = V(t.rand(1), requires_grad = True)
w = V(t.rand(1), requires_grad = True)
y = w * x
z = y + b

In [37]:
x.is_leaf, w.is_leaf, b.is_leaf

(True, True, True)

In [39]:
z.grad_fn

In [41]:
z.grad_fn.next_functions

((<MulBackward0 at 0x1469b3dcaf0>, 0), (<AccumulateGrad at 0x1469af38670>, 0))

In [47]:
z.backward(retain_graph = True)
w.grad

tensor([1.])

In [49]:
z.backward()
w.grad

tensor([2.])

In [51]:
x = V(t.ones(1))
w = V(t.rand(1), requires_grad = True)
y = x * w
x.requires_grad, w.requires_grad, y.requires_grad

(False, True, True)

In [53]:
x.volatile, w.volatile, y.volatile

C:\Users\sifanzhang\AppData\Local\Temp\ipykernel_23768\3452568332.py:1: UserWarning: volatile was removed (Variable.volatile is always False)
  x.volatile, w.volatile, y.volatile


(False, False, False)

In [55]:
x = V(t.ones(3), requires_grad = True)
w = V(t.rand(3), requires_grad = True)
y = x * w

z = y.sum()

In [57]:
x


tensor([1., 1., 1.], requires_grad=True)

In [59]:
y

tensor([0.5829, 0.0874, 0.8013], grad_fn=<MulBackward0>)

In [61]:
w

tensor([0.5829, 0.0874, 0.8013], requires_grad=True)

In [63]:
z.backward()

In [65]:
x.grad, y.grad, w.grad

C:\Users\sifanzhang\AppData\Local\Temp\ipykernel_23768\414268609.py:1: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the .grad field to be populated for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more informations. (Triggered internally at aten\src\ATen/core/TensorBody.h:494.)
  x.grad, y.grad, w.grad


(tensor([0.5829, 0.0874, 0.8013]), None, tensor([1., 1., 1.]))

In [67]:
x = V(t.ones(3), requires_grad = True)
w = V(t.rand(3), requires_grad = True)
y = x * w

z = y.sum()
t.autograd.grad(z, y)

(tensor([1., 1., 1.]),)

In [69]:
def variable_hook(grad):
    print("y的梯度: \r\n", grad)

x = V(t.ones(3), requires_grad = True)
w = V(t.rand(3), requires_grad = True)
y = x * w
hook_handle = y.register_hook(variable_hook)

z = y.sum()
z.backward()

hook_handle.remove()

y的梯度: 
 tensor([1., 1., 1.])


In [75]:
x = V(t.arange(0, 3).float(), requires_grad = True)
y = x ** 2 + x * 2
z = y.sum()
y_grad_variables = V(t.Tensor([1, 1, 1]))
y.backward(y_grad_variables)
x.grad

tensor([2., 4., 6.])