In [1]:
import torch
import torch.nn as nn
import torchvision
import torchvision.transforms as transforms


In [3]:
# Hyper-parameters 
input_size = 28 * 28    # 784
num_classes = 10
num_epochs = 5
batch_size = 100
learning_rate = 0.001

In [5]:

# MNIST dataset (images and labels)
train_dataset = torchvision.datasets.MNIST(root='/data', 
                                           train=True, 
                                           transform=transforms.ToTensor(),
                                           download=True)

test_dataset = torchvision.datasets.MNIST(root='/data', 
                                          train=False, 
                                          transform=transforms.ToTensor())

# Data loader (input pipeline)
train_loader = torch.utils.data.DataLoader(dataset=train_dataset, 
                                           batch_size=batch_size, 
                                           shuffle=True)

test_loader = torch.utils.data.DataLoader(dataset=test_dataset, 
                                          batch_size=batch_size, 
                                          shuffle=False)


Failed to download (trying next):
HTTP Error 403: Forbidden



100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 9912422/9912422 [00:03<00:00, 3083157.60it/s]


Extracting /data\MNIST\raw\train-images-idx3-ubyte.gz to /data\MNIST\raw

Failed to download (trying next):
HTTP Error 403: Forbidden



100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 28881/28881 [00:00<00:00, 130063.51it/s]


Extracting /data\MNIST\raw\train-labels-idx1-ubyte.gz to /data\MNIST\raw

Failed to download (trying next):
HTTP Error 403: Forbidden



100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1648877/1648877 [00:01<00:00, 1068925.01it/s]


Extracting /data\MNIST\raw\t10k-images-idx3-ubyte.gz to /data\MNIST\raw

Failed to download (trying next):
HTTP Error 403: Forbidden



100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4542/4542 [00:00<00:00, 4536920.40it/s]

Extracting /data\MNIST\raw\t10k-labels-idx1-ubyte.gz to /data\MNIST\raw



In [9]:
model = nn.Linear(input_size, num_classes)

In [15]:

# Loss and optimizer
# nn.CrossEntropyLoss() computes softmax internally
criterion = nn.CrossEntropyLoss()  
optimizer = torch.optim.SGD(model.parameters(), lr=learning_rate)  


In [23]:
for i, (images, labels) in enumerate(train_loader):
    break
print(images.shape)
images = images.reshape(-1, input_size)

print(images)
print(images.shape)

torch.Size([100, 1, 28, 28])
tensor([[0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        ...,
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.]])
torch.Size([100, 784])


In [25]:

# Train the model
total_step = len(train_loader)
for epoch in range(num_epochs):
    for i, (images, labels) in enumerate(train_loader):
        # Reshape images to (batch_size, input_size)
        images = images.reshape(-1, input_size)
        
        # Forward pass
        outputs = model(images)
        loss = criterion(outputs, labels)
        
        # Backward and optimize
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()
        
        if (i+1) % 100 == 0:
            print ('Epoch [{}/{}], Step [{}/{}], Loss: {:.4f}' 
                   .format(epoch+1, num_epochs, i+1, total_step, loss.item()))


Epoch [1/5], Step [100/600], Loss: 2.2119
Epoch [1/5], Step [200/600], Loss: 2.1050
Epoch [1/5], Step [300/600], Loss: 2.0824
Epoch [1/5], Step [400/600], Loss: 1.9850
Epoch [1/5], Step [500/600], Loss: 1.8948
Epoch [1/5], Step [600/600], Loss: 1.7563
Epoch [2/5], Step [100/600], Loss: 1.7831
Epoch [2/5], Step [200/600], Loss: 1.6833
Epoch [2/5], Step [300/600], Loss: 1.5648
Epoch [2/5], Step [400/600], Loss: 1.5674
Epoch [2/5], Step [500/600], Loss: 1.5668
Epoch [2/5], Step [600/600], Loss: 1.5637
Epoch [3/5], Step [100/600], Loss: 1.4031
Epoch [3/5], Step [200/600], Loss: 1.4004
Epoch [3/5], Step [300/600], Loss: 1.3654
Epoch [3/5], Step [400/600], Loss: 1.3296
Epoch [3/5], Step [500/600], Loss: 1.2382
Epoch [3/5], Step [600/600], Loss: 1.2155
Epoch [4/5], Step [100/600], Loss: 1.2592
Epoch [4/5], Step [200/600], Loss: 1.2371
Epoch [4/5], Step [300/600], Loss: 1.2632
Epoch [4/5], Step [400/600], Loss: 1.2414
Epoch [4/5], Step [500/600], Loss: 1.0418
Epoch [4/5], Step [600/600], Loss:

In [37]:
for images, labels in test_loader:
    break
images = images.reshape(-1, input_size)
outputs = model(images)
print(outputs.shape)
a, b = torch.max(outputs.data, 1)
print(a)
print(b)

torch.Size([100, 10])
tensor([2.9556, 1.4110, 2.2362, 2.9545, 1.8205, 2.7986, 1.3135, 1.2086, 0.7847,
        1.9443, 3.3458, 0.8363, 2.1264, 2.9698, 2.6339, 1.4017, 1.4938, 2.7206,
        1.1951, 1.8575, 1.5707, 2.1467, 1.0089, 1.2129, 1.3625, 4.0520, 1.7896,
        2.3757, 2.7827, 1.4505, 2.2126, 1.0999, 2.4560, 1.9094, 1.7703, 2.4034,
        2.2524, 2.0297, 1.0409, 3.0094, 1.4867, 1.9337, 2.1093, 1.1147, 1.2613,
        1.6455, 0.8726, 1.4911, 2.7549, 2.4140, 2.0019, 1.8861, 1.3213, 1.0768,
        1.1737, 1.5254, 2.7508, 2.3441, 2.0822, 0.3754, 1.8618, 1.2002, 0.9063,
        1.2373, 1.6780, 0.9123, 0.9118, 2.0263, 2.7916, 2.5636, 2.7137, 4.3931,
        1.9308, 0.9875, 2.2181, 1.8041, 2.3047, 1.5662, 1.0178, 3.1810, 1.8184,
        2.3726, 3.8270, 2.2025, 0.8348, 2.9002, 3.0308, 1.8665, 2.7231, 3.0188,
        2.9419, 2.5745, 0.7163, 2.6400, 1.8741, 2.3668, 0.6184, 1.4236, 1.8758,
        2.0224])
tensor([7, 2, 1, 0, 4, 1, 4, 9, 2, 9, 0, 0, 9, 0, 1, 3, 9, 7, 3, 4, 9, 6, 6, 5,
 

In [39]:
with torch.no_grad():
    correct = 0
    total = 0
    for images, labels in test_loader:
        images = images.reshape(-1, input_size)
        outputs = model(images)
        _, predicted = torch.max(outputs.data, 1)
        total += labels.size(0)
        correct += (predicted == labels).sum()

    print('Accuracy of the model on the 10000 test images: {} %'.format(100 * correct / total))


Accuracy of the model on the 10000 test images: 83.02999877929688 %


In [41]:
# Save the model checkpoint
torch.save(model.state_dict(), 'model.ckpt')