In [1]:
import os
import torch
from torch import nn
from torch.utils.data import DataLoader
from torchvision import datasets, transforms

In [3]:
device = (
    "cuda"
    if torch.cuda.is_available()
    else "mps"
    if torch.backends.mps.is_available()
    else "cpu"
)
print(f"Using {device} device")

Using cpu device


In [9]:
class NeuralNetwork(nn.Module):
    def __init__(self):
        super().__init__()
        self.flatten = nn.Flatten()
        self.linear_relu_stack = nn.Sequential(
            nn.Linear(28*28, 512),
            nn.ReLU(),
            nn.Linear(512, 512),
            nn.ReLU(),
            nn.Linear(512, 10)
        )

    def forward(self, x):
        x = self.flatten(x)
        logits = self.linear_relu_stack(x)
        return logits



In [11]:
model = NeuralNetwork().to(device)
print(model)

NeuralNetwork(
  (flatten): Flatten(start_dim=1, end_dim=-1)
  (linear_relu_stack): Sequential(
    (0): Linear(in_features=784, out_features=512, bias=True)
    (1): ReLU()
    (2): Linear(in_features=512, out_features=512, bias=True)
    (3): ReLU()
    (4): Linear(in_features=512, out_features=10, bias=True)
  )
)


In [15]:
X = torch.rand(1, 28, 28, device=device)
logits = model(X)
print(logits)
pred_probab = nn.Softmax(dim=1)(logits)
print(pred_probab)
y_pred = pred_probab.argmax(1)
y_pred

tensor([[ 0.0323, -0.0062,  0.0159,  0.0091, -0.0016,  0.0296,  0.0304, -0.1042,
          0.0709, -0.0233]], grad_fn=<AddmmBackward0>)
tensor([[0.1026, 0.0988, 0.1010, 0.1003, 0.0992, 0.1024, 0.1024, 0.0895, 0.1067,
         0.0971]], grad_fn=<SoftmaxBackward0>)


tensor([8])

# Model Layers

In [24]:
input_image = torch.rand(3, 28, 28)
print(input_image.size())

torch.Size([3, 28, 28])


In [28]:
flatten = nn.Flatten()
flat_image = flatten(input_image)
print(flat_image.size())

torch.Size([3, 784])


In [30]:
layer1 = nn.Linear(in_features = 28 * 28, out_features = 20)
hidden1 = layer1(flat_image)
print(hidden1.size(), hidden1)

torch.Size([3, 20]) tensor([[ 0.5721, -0.3378,  0.2011,  0.7399, -0.4280, -0.2504,  0.0774,  0.5536,
         -0.1068, -0.1344, -0.3614,  0.1445,  0.4435, -0.1851,  0.0337,  0.1948,
          0.2411,  0.3593, -0.0502,  0.4875],
        [ 0.5492, -0.3913,  0.1249,  0.5547, -0.1225, -0.3004, -0.1348,  0.6056,
         -0.0979, -0.0814, -0.1862, -0.0064,  0.1608, -0.1174,  0.0693, -0.1935,
          0.4225, -0.0411,  0.1246,  0.5634],
        [ 0.2972, -0.0642,  0.3700,  0.5138, -0.5365, -0.2348, -0.0669,  0.7572,
          0.0417,  0.0032, -0.0776,  0.1724,  0.2319, -0.1522, -0.0129,  0.0290,
          0.0930,  0.5025,  0.0104,  0.0256]], grad_fn=<AddmmBackward0>)


In [32]:
print(f"Before ReLU: {hidden1}\n\n")
hidden1 = nn.ReLU()(hidden1)
print(f"After ReLU: {hidden1}\n\n")

Before ReLU: tensor([[ 0.5721, -0.3378,  0.2011,  0.7399, -0.4280, -0.2504,  0.0774,  0.5536,
         -0.1068, -0.1344, -0.3614,  0.1445,  0.4435, -0.1851,  0.0337,  0.1948,
          0.2411,  0.3593, -0.0502,  0.4875],
        [ 0.5492, -0.3913,  0.1249,  0.5547, -0.1225, -0.3004, -0.1348,  0.6056,
         -0.0979, -0.0814, -0.1862, -0.0064,  0.1608, -0.1174,  0.0693, -0.1935,
          0.4225, -0.0411,  0.1246,  0.5634],
        [ 0.2972, -0.0642,  0.3700,  0.5138, -0.5365, -0.2348, -0.0669,  0.7572,
          0.0417,  0.0032, -0.0776,  0.1724,  0.2319, -0.1522, -0.0129,  0.0290,
          0.0930,  0.5025,  0.0104,  0.0256]], grad_fn=<AddmmBackward0>)


After ReLU: tensor([[0.5721, 0.0000, 0.2011, 0.7399, 0.0000, 0.0000, 0.0774, 0.5536, 0.0000,
         0.0000, 0.0000, 0.1445, 0.4435, 0.0000, 0.0337, 0.1948, 0.2411, 0.3593,
         0.0000, 0.4875],
        [0.5492, 0.0000, 0.1249, 0.5547, 0.0000, 0.0000, 0.0000, 0.6056, 0.0000,
         0.0000, 0.0000, 0.0000, 0.1608, 0.0000, 0.06

In [34]:
seq_modules = nn.Sequential(
    flatten,
    layer1,
    nn.ReLU(),
    nn.Linear(20, 10)
)

input_image = torch.rand(3, 28, 28)
logits = seq_modules(input_image)
print(logits)

tensor([[-3.2853e-02, -2.2793e-01, -6.9081e-02, -3.5297e-02, -1.0422e-01,
          1.5244e-01, -2.9044e-02,  1.8773e-01,  1.5416e-02,  4.5994e-01],
        [-2.0958e-02, -3.6648e-01, -3.0279e-02, -5.5924e-04, -8.0111e-02,
          1.3686e-01,  7.7066e-02,  1.9329e-01, -1.0135e-01,  5.3152e-01],
        [ 9.3064e-02, -3.6606e-01, -4.0552e-02, -1.0528e-02, -2.6645e-01,
          1.3931e-01, -8.6302e-02,  1.9515e-01,  1.8211e-01,  6.3218e-01]],
       grad_fn=<AddmmBackward0>)


In [36]:
softmax = nn.Softmax(dim=1)
pred_probab = softmax(logits)
print(pred_probab)

tensor([[0.0921, 0.0758, 0.0888, 0.0919, 0.0858, 0.1109, 0.0925, 0.1148, 0.0967,
         0.1508],
        [0.0923, 0.0653, 0.0914, 0.0942, 0.0870, 0.1081, 0.1018, 0.1143, 0.0852,
         0.1604],
        [0.1010, 0.0638, 0.0883, 0.0910, 0.0705, 0.1057, 0.0844, 0.1118, 0.1104,
         0.1731]], grad_fn=<SoftmaxBackward0>)


# Model Parameters

In [39]:
print(f"Model structure: {model}\n\n")

for name, param in model.named_parameters():
    print(f"Layer: {name} | Size: {param.size()} | Values : {param[:2]} \n")

Model structure: NeuralNetwork(
  (flatten): Flatten(start_dim=1, end_dim=-1)
  (linear_relu_stack): Sequential(
    (0): Linear(in_features=784, out_features=512, bias=True)
    (1): ReLU()
    (2): Linear(in_features=512, out_features=512, bias=True)
    (3): ReLU()
    (4): Linear(in_features=512, out_features=10, bias=True)
  )
)


Layer: linear_relu_stack.0.weight | Size: torch.Size([512, 784]) | Values : tensor([[-0.0080, -0.0081, -0.0290,  ..., -0.0042,  0.0213,  0.0042],
        [-0.0296,  0.0302,  0.0254,  ..., -0.0042,  0.0038, -0.0174]],
       grad_fn=<SliceBackward0>) 

Layer: linear_relu_stack.0.bias | Size: torch.Size([512]) | Values : tensor([-0.0066,  0.0329], grad_fn=<SliceBackward0>) 

Layer: linear_relu_stack.2.weight | Size: torch.Size([512, 512]) | Values : tensor([[-0.0019,  0.0276, -0.0065,  ...,  0.0411, -0.0067,  0.0381],
        [ 0.0042, -0.0022,  0.0112,  ...,  0.0428, -0.0423,  0.0423]],
       grad_fn=<SliceBackward0>) 

Layer: linear_relu_stack.2.bias | 